package vn.org.thn.app.base.core.entity;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Common audit columns for MyBatis-mapped entities - createdAt/updatedAt/createdBy/updatedBy plus
 * a soft-delete flag. Deliberately has no {@code id} field: primary keys vary too much between
 * entities (a single auto-increment {@code Long}, a business-assigned {@code String}/UUID, or a
 * composite key spread across several fields like {@link vn.org.thn.service.base.i18n.Translate}),
 * so each entity declares its own {@code @Id} (and {@code @GeneratedValue} if it is DB-generated)
 * directly - extending this class only ever adds the audit columns, never forces a particular key
 * shape.
 * <p>
 * Extend this in each service's entity classes (which still need their own {@code @Entity}/
 * {@code @Table} and their own {@code @Id} field(s)) and map these fields to the corresponding
 * table columns (created_at, updated_at, created_by, updated_by, deleted). None of the four
 * timestamp/actor fields are auto-populated - there is no audit interceptor wired up in
 * {@code base} - so calling code must set them explicitly before {@code save()}. Likewise
 * {@code deleted} is a plain column: no query in {@code base} filters it out automatically: a
 * caller that wants soft-delete semantics must add that condition itself (e.g.
 * {@code .eq(Entity::isDeleted, false)}) and set the flag instead of calling {@code deleteById()}.
 * <p>
 * Getters/setters generated by {@link Data} - {@code isDeleted()}/{@code setDeleted(boolean)} for
 * the primitive {@code boolean} field, matching the naming this class had before the switch to
 * Lombok. A subclass that adds {@code @Data} of its own (e.g. {@code Article}) should also add
 * {@code @EqualsAndHashCode(callSuper = true)}/{@code @ToString(callSuper = true)} - otherwise its
 * generated {@code equals}/{@code hashCode}/{@code toString} silently ignore these 5 inherited
 * fields, since Lombok never includes superclass fields unless told to.
 */
@Data
public abstract class BaseEntity {

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String createdBy;
    private String updatedBy;
    private boolean deleted = false;
}
