package vn.org.thn.app.base.core.entity;

import lombok.Data;

import vn.org.thn.app.base.core.context.UserContext;

import java.time.LocalDateTime;

/**
 * Common audit columns for MyBatis-mapped entities - createdAt/updatedAt/createdBy/updatedBy plus
 * a soft-delete flag. Deliberately has no {@code id} field: primary keys vary too much between
 * entities (a single auto-increment {@code Long}, a business-assigned {@code String}/UUID, or a
 * composite key spread across several fields like {@link vn.org.thn.service.base.i18n.Translate}),
 * so each entity declares its own {@code @Id} (and {@code @GeneratedValue} if it is DB-generated)
 * directly - extending this class only ever adds the audit columns, never forces a particular key
 * shape.
 * <p>
 * Extend this in each service's entity classes (which still need their own {@code @Entity}/
 * {@code @Table} and their own {@code @Id} field(s)) and map these fields to the corresponding
 * table columns (created_at, updated_at, created_by, updated_by, deleted).
 * The timestamp and actor fields are automatically managed by {@link vn.org.thn.app.base.persistence.executor.InsertExecutor}
 * and {@link vn.org.thn.app.base.persistence.executor.BatchInsertExecutor}:
 * <ul>
 *   <li><b>INSERT</b>: automatically sets {@code createdAt} (if null), {@code updatedAt} (if null),
 *       {@code createdBy} (from {@link vn.org.thn.app.base.core.context.UserContext} or "system"),
 *       and {@code updatedBy}.</li>
 *   <li><b>UPDATE</b>: automatically updates {@code updatedAt} and {@code updatedBy}, while protecting
 *       {@code createdAt} and {@code createdBy} from modification.</li>
 * </ul>
 * Likewise {@code deleted} defaults to {@code false}: a caller that wants soft-delete semantics can
 * add that condition (e.g. {@code .eq(Entity::isDeleted, false)}) and set the flag instead of calling {@code deleteById()}.
 * <p>
 * Getters/setters generated by {@link Data} - {@code isDeleted()}/{@code setDeleted(boolean)} for
 * the primitive {@code boolean} field, matching the naming this class had before the switch to
 * Lombok. A subclass that adds {@code @Data} of its own (e.g. {@code Article}) should also add
 * {@code @EqualsAndHashCode(callSuper = true)}/{@code @ToString(callSuper = true)} - otherwise its
 * generated {@code equals}/{@code hashCode}/{@code toString} silently ignore these 5 inherited
 * fields, since Lombok never includes superclass fields unless told to.
 */
@Data
public abstract class BaseEntity {

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String createdBy;
    private String updatedBy;
    private boolean deleted = false;

    /**
     * Automatically populates audit fields before INSERT:
     * sets createdAt, updatedAt, createdBy, and updatedBy if not already provided.
     */
    public static void populateInsertAudit(BaseEntity entity) {
        if (entity == null) {
            return;
        }
        LocalDateTime now = LocalDateTime.now();
        String currentUser = UserContext.getCurrentUser();
        if (currentUser == null || currentUser.isBlank()) {
            currentUser = "system";
        }
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        if (entity.getUpdatedAt() == null) {
            entity.setUpdatedAt(entity.getCreatedAt());
        }
        if (entity.getCreatedBy() == null || entity.getCreatedBy().isBlank()) {
            entity.setCreatedBy(currentUser);
        }
        if (entity.getUpdatedBy() == null || entity.getUpdatedBy().isBlank()) {
            entity.setUpdatedBy(entity.getCreatedBy());
        }
    }

    /**
     * Automatically populates audit fields before UPDATE:
     * sets updatedAt and updatedBy.
     */
    public static void populateUpdateAudit(BaseEntity entity) {
        if (entity == null) {
            return;
        }
        LocalDateTime now = LocalDateTime.now();
        String currentUser = UserContext.getCurrentUser();
        if (currentUser == null || currentUser.isBlank()) {
            currentUser = "system";
        }
        entity.setUpdatedAt(now);
        entity.setUpdatedBy(currentUser);
    }
}
