CREATE TABLE tbl_user
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR2(100) NOT NULL UNIQUE,
    email      VARCHAR2(150),
    full_name  VARCHAR2(150),
    status     VARCHAR2(50) DEFAULT 'ACTIVE',
    role       VARCHAR2(50) DEFAULT 'USER',
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0
);
