package vn.org.thn.app.base.core.constant;

/**
 * Header-name constants shared across services. Prefer these over repeating the raw literal
 * string in controller/filter code, so a rename only touches one place.
 * <p>
 * Page-size defaults used to be duplicated here as well ({@code DEFAULT_PAGE_SIZE}/
 * {@code MAX_PAGE_SIZE}); they were removed since {@link vn.org.thn.app.base.core.dto.page.PageRequest}
 * already owns those same values ({@code DEFAULT_SIZE}/{@code MAX_SIZE}) and is the copy actually
 * wired into pagination clamping - two constants for the same number is a drift risk with no benefit.
 */
public final class CommonConstants {

    private CommonConstants() {
    }

    /**
     * Standard "Authorization" HTTP header name, for a consuming service that reads/writes it
     * manually (e.g. tests, manual HTTP client calls). {@code base} does carry its own JWT
     * authentication/authorization now ({@link vn.org.thn.app.base.security.SecurityAutoConfiguration}
     * and the rest of {@code base.security.*}, added 2026-09-13 for the 2026-09-12 review's Critical
     * finding #2) - but Spring Security's OAuth2 resource server filter parses this header
     * internally via its own {@code BearerTokenResolver}, so that path doesn't go through this
     * constant.
     */
    public static final String AUTHORIZATION_HEADER = "Authorization";

    /** "Bearer " prefix conventionally used with {@link #AUTHORIZATION_HEADER}. */
    public static final String BEARER_PREFIX = "Bearer ";

    /** Correlation-id header read/generated by {@link vn.org.thn.app.base.web.filter.RequestContextFilter}. */
    public static final String REQUEST_ID_HEADER = "X-Request-Id";
}
