package vn.org.thn.app.base.core.constant;

/**
 * Header-name constants shared across services. Prefer these over repeating the raw literal
 * string in controller/filter code, so a rename only touches one place.
 * <p>
 * Page-size defaults used to be duplicated here as well ({@code DEFAULT_PAGE_SIZE}/
 * {@code MAX_PAGE_SIZE}); they were removed since {@link vn.org.thn.service.base.dto.page.PageRequest}
 * already owns those same values ({@code DEFAULT_SIZE}/{@code MAX_SIZE}) and is the copy actually
 * wired into pagination clamping - two constants for the same number is a drift risk with no benefit.
 */
public final class CommonConstants {

    private CommonConstants() {
    }

    /**
     * Standard "Authorization" HTTP header name, for a consuming service that reads/writes it
     * manually (this module itself carries no security/JWT logic - see {@link vn.org.thn.service.base.IBase}'s
     * javadoc for why that responsibility was dropped from {@code base}).
     */
    public static final String AUTHORIZATION_HEADER = "Authorization";

    /** "Bearer " prefix conventionally used with {@link #AUTHORIZATION_HEADER}. */
    public static final String BEARER_PREFIX = "Bearer ";

    /** Correlation-id header read/generated by {@link vn.org.thn.service.base.web.RequestContextFilter}. */
    public static final String REQUEST_ID_HEADER = "X-Request-Id";
}
